/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package models;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-06-15")
public class Kind implements org.apache.thrift.TBase<Kind, Kind._Fields>, java.io.Serializable, Cloneable, Comparable<Kind> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Kind");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField SONGS_FIELD_DESC = new org.apache.thrift.protocol.TField("songs", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField AMOUNT_SONGS_FIELD_DESC = new org.apache.thrift.protocol.TField("amount_songs", org.apache.thrift.protocol.TType.I32, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new KindStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new KindTupleSchemeFactory();

  public java.lang.String id; // required
  public java.lang.String name; // required
  public java.util.List<models.Referencer> songs; // required
  public int amount_songs; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    NAME((short)2, "name"),
    SONGS((short)3, "songs"),
    AMOUNT_SONGS((short)4, "amount_songs");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // NAME
          return NAME;
        case 3: // SONGS
          return SONGS;
        case 4: // AMOUNT_SONGS
          return AMOUNT_SONGS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __AMOUNT_SONGS_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SONGS, new org.apache.thrift.meta_data.FieldMetaData("songs", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, models.Referencer.class))));
    tmpMap.put(_Fields.AMOUNT_SONGS, new org.apache.thrift.meta_data.FieldMetaData("amount_songs", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Kind.class, metaDataMap);
  }

  public Kind() {
  }

  public Kind(
    java.lang.String id,
    java.lang.String name,
    java.util.List<models.Referencer> songs,
    int amount_songs)
  {
    this();
    this.id = id;
    this.name = name;
    this.songs = songs;
    this.amount_songs = amount_songs;
    setAmount_songsIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Kind(Kind other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetId()) {
      this.id = other.id;
    }
    if (other.isSetName()) {
      this.name = other.name;
    }
    if (other.isSetSongs()) {
      java.util.List<models.Referencer> __this__songs = new java.util.ArrayList<models.Referencer>(other.songs.size());
      for (models.Referencer other_element : other.songs) {
        __this__songs.add(new models.Referencer(other_element));
      }
      this.songs = __this__songs;
    }
    this.amount_songs = other.amount_songs;
  }

  public Kind deepCopy() {
    return new Kind(this);
  }

  @Override
  public void clear() {
    this.id = null;
    this.name = null;
    this.songs = null;
    setAmount_songsIsSet(false);
    this.amount_songs = 0;
  }

  public java.lang.String getId() {
    return this.id;
  }

  public Kind setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  public void unsetId() {
    this.id = null;
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return this.id != null;
  }

  public void setIdIsSet(boolean value) {
    if (!value) {
      this.id = null;
    }
  }

  public java.lang.String getName() {
    return this.name;
  }

  public Kind setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  public void unsetName() {
    this.name = null;
  }

  /** Returns true if field name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.name = null;
    }
  }

  public int getSongsSize() {
    return (this.songs == null) ? 0 : this.songs.size();
  }

  public java.util.Iterator<models.Referencer> getSongsIterator() {
    return (this.songs == null) ? null : this.songs.iterator();
  }

  public void addToSongs(models.Referencer elem) {
    if (this.songs == null) {
      this.songs = new java.util.ArrayList<models.Referencer>();
    }
    this.songs.add(elem);
  }

  public java.util.List<models.Referencer> getSongs() {
    return this.songs;
  }

  public Kind setSongs(java.util.List<models.Referencer> songs) {
    this.songs = songs;
    return this;
  }

  public void unsetSongs() {
    this.songs = null;
  }

  /** Returns true if field songs is set (has been assigned a value) and false otherwise */
  public boolean isSetSongs() {
    return this.songs != null;
  }

  public void setSongsIsSet(boolean value) {
    if (!value) {
      this.songs = null;
    }
  }

  public int getAmount_songs() {
    return this.amount_songs;
  }

  public Kind setAmount_songs(int amount_songs) {
    this.amount_songs = amount_songs;
    setAmount_songsIsSet(true);
    return this;
  }

  public void unsetAmount_songs() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __AMOUNT_SONGS_ISSET_ID);
  }

  /** Returns true if field amount_songs is set (has been assigned a value) and false otherwise */
  public boolean isSetAmount_songs() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __AMOUNT_SONGS_ISSET_ID);
  }

  public void setAmount_songsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __AMOUNT_SONGS_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.String)value);
      }
      break;

    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((java.lang.String)value);
      }
      break;

    case SONGS:
      if (value == null) {
        unsetSongs();
      } else {
        setSongs((java.util.List<models.Referencer>)value);
      }
      break;

    case AMOUNT_SONGS:
      if (value == null) {
        unsetAmount_songs();
      } else {
        setAmount_songs((java.lang.Integer)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case NAME:
      return getName();

    case SONGS:
      return getSongs();

    case AMOUNT_SONGS:
      return getAmount_songs();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case NAME:
      return isSetName();
    case SONGS:
      return isSetSongs();
    case AMOUNT_SONGS:
      return isSetAmount_songs();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Kind)
      return this.equals((Kind)that);
    return false;
  }

  public boolean equals(Kind that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true && this.isSetId();
    boolean that_present_id = true && that.isSetId();
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (!this.id.equals(that.id))
        return false;
    }

    boolean this_present_name = true && this.isSetName();
    boolean that_present_name = true && that.isSetName();
    if (this_present_name || that_present_name) {
      if (!(this_present_name && that_present_name))
        return false;
      if (!this.name.equals(that.name))
        return false;
    }

    boolean this_present_songs = true && this.isSetSongs();
    boolean that_present_songs = true && that.isSetSongs();
    if (this_present_songs || that_present_songs) {
      if (!(this_present_songs && that_present_songs))
        return false;
      if (!this.songs.equals(that.songs))
        return false;
    }

    boolean this_present_amount_songs = true;
    boolean that_present_amount_songs = true;
    if (this_present_amount_songs || that_present_amount_songs) {
      if (!(this_present_amount_songs && that_present_amount_songs))
        return false;
      if (this.amount_songs != that.amount_songs)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetId()) ? 131071 : 524287);
    if (isSetId())
      hashCode = hashCode * 8191 + id.hashCode();

    hashCode = hashCode * 8191 + ((isSetName()) ? 131071 : 524287);
    if (isSetName())
      hashCode = hashCode * 8191 + name.hashCode();

    hashCode = hashCode * 8191 + ((isSetSongs()) ? 131071 : 524287);
    if (isSetSongs())
      hashCode = hashCode * 8191 + songs.hashCode();

    hashCode = hashCode * 8191 + amount_songs;

    return hashCode;
  }

  @Override
  public int compareTo(Kind other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetName()).compareTo(other.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, other.name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSongs()).compareTo(other.isSetSongs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSongs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.songs, other.songs);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetAmount_songs()).compareTo(other.isSetAmount_songs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAmount_songs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.amount_songs, other.amount_songs);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Kind(");
    boolean first = true;

    sb.append("id:");
    if (this.id == null) {
      sb.append("null");
    } else {
      sb.append(this.id);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("name:");
    if (this.name == null) {
      sb.append("null");
    } else {
      sb.append(this.name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("songs:");
    if (this.songs == null) {
      sb.append("null");
    } else {
      sb.append(this.songs);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("amount_songs:");
    sb.append(this.amount_songs);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (id == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'id' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class KindStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public KindStandardScheme getScheme() {
      return new KindStandardScheme();
    }
  }

  private static class KindStandardScheme extends org.apache.thrift.scheme.StandardScheme<Kind> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Kind struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.id = iprot.readString();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SONGS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.songs = new java.util.ArrayList<models.Referencer>(_list0.size);
                models.Referencer _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new models.Referencer();
                  _elem1.read(iprot);
                  struct.songs.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setSongsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // AMOUNT_SONGS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.amount_songs = iprot.readI32();
              struct.setAmount_songsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Kind struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.id != null) {
        oprot.writeFieldBegin(ID_FIELD_DESC);
        oprot.writeString(struct.id);
        oprot.writeFieldEnd();
      }
      if (struct.name != null) {
        oprot.writeFieldBegin(NAME_FIELD_DESC);
        oprot.writeString(struct.name);
        oprot.writeFieldEnd();
      }
      if (struct.songs != null) {
        oprot.writeFieldBegin(SONGS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.songs.size()));
          for (models.Referencer _iter3 : struct.songs)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(AMOUNT_SONGS_FIELD_DESC);
      oprot.writeI32(struct.amount_songs);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class KindTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public KindTupleScheme getScheme() {
      return new KindTupleScheme();
    }
  }

  private static class KindTupleScheme extends org.apache.thrift.scheme.TupleScheme<Kind> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Kind struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.id);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetName()) {
        optionals.set(0);
      }
      if (struct.isSetSongs()) {
        optionals.set(1);
      }
      if (struct.isSetAmount_songs()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetName()) {
        oprot.writeString(struct.name);
      }
      if (struct.isSetSongs()) {
        {
          oprot.writeI32(struct.songs.size());
          for (models.Referencer _iter4 : struct.songs)
          {
            _iter4.write(oprot);
          }
        }
      }
      if (struct.isSetAmount_songs()) {
        oprot.writeI32(struct.amount_songs);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Kind struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.id = iprot.readString();
      struct.setIdIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.name = iprot.readString();
        struct.setNameIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.songs = new java.util.ArrayList<models.Referencer>(_list5.size);
          models.Referencer _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new models.Referencer();
            _elem6.read(iprot);
            struct.songs.add(_elem6);
          }
        }
        struct.setSongsIsSet(true);
      }
      if (incoming.get(2)) {
        struct.amount_songs = iprot.readI32();
        struct.setAmount_songsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

